import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#570000",
        "primary-container": "#800000",
        "on-primary": "#ffffff",
        "on-primary-container": "#ff8371",
        "primary-fixed": "#ffdad4",
        "primary-fixed-dim": "#ffb4a8",
        "on-primary-fixed": "#410000",
        "on-primary-fixed-variant": "#8f0f07",
        secondary: "#785900",
        "secondary-container": "#fdc003",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#6c5000",
        "secondary-fixed": "#ffdf9e",
        "secondary-fixed-dim": "#fabd00",
        "on-secondary-fixed": "#261a00",
        "on-secondary-fixed-variant": "#5b4300",
        tertiary: "#002e06",
        "tertiary-container": "#00470e",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#69b966",
        "tertiary-fixed": "#a3f69c",
        "tertiary-fixed-dim": "#88d982",
        "on-tertiary-fixed": "#002204",
        "on-tertiary-fixed-variant": "#005312",
        background: "#fbf9f8",
        "on-background": "#1b1c1c",
        surface: "#fbf9f8",
        "on-surface": "#1b1c1c",
        "surface-variant": "#e4e2e1",
        "on-surface-variant": "#5a413d",
        "surface-bright": "#fbf9f8",
        "surface-dim": "#dcd9d9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae8e7",
        "surface-container-highest": "#e4e2e1",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f3f0f0",
        "inverse-primary": "#ffb4a8",
        "surface-tint": "#b22b1d",
        outline: "#8e706c",
        "outline-variant": "#e2bfb9",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "16px",
        gutter: "20px",
        md: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        lg: "40px",
        xl: "64px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Work Sans", "sans-serif"],
        label: ["JetBrains Mono", "monospace"],
        "headline-lg": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "headline-sm": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "body-lg": ["Work Sans", "sans-serif"],
        "body-md": ["Work Sans", "sans-serif"],
        "body-sm": ["Work Sans", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
